print('\033[02;34m Enter text and find out more details about the text')
palavra = str(input('type the word or phrase:')).strip()
print('\033[02;35m The text entered has',len(palavra) - palavra.count(' '),'letters')
print('The text entered has',palavra.count('a'),'letter(s) A')
print('\033[02;33m The text entered in capital letter(s) is:',palavra.upper())
print('The text entered in lowercase letter(s) is:',palavra.lower())
print('\033[02;32m With each initial letter of the word in capital letters:',palavra.title())
print('Your first name has',palavra.find(' '),'letters')
separa = palavra.split()
print(f'Seu primeiro nome é {separa[0]}',len(separa[0]))